############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "Showcase"
pageRef = "/showcase"
weight = 3

# [[main]]
# name = "Docs"
# pageRef = "/docs"
# weight = 2